/**
 * The contents of this file are subject to the OpenMRS Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://license.openmrs.org
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * Copyright (C) OpenMRS, LLC.  All Rights Reserved.
 */

package org.openmrs.module.clinicalsummary.rule;

public interface EvaluableNameConstants {

	String ADMITTED_TO_HOSPITAL = "ADMITTED TO HOSPITAL";

	String ALL = "ALL";

	String AMPHOTERICIN_B = "AMPHOTERICIN B";

	String ANTENATAL_STUDY_CONTROL_GROUP = "ANTENATAL CONTROL";

	String ANTENATAL_STUDY_INTERVENTION_GROUP = "ANTENATAL INTERVENTION";

	String ANTI_D_RH_IGG_GIVEN_AT_28_GESTATION_WEEKS = "ANTI-D RH IGG GIVEN AT 28 GESTATION WEEKS ";
	//
	String ANTIRETROVIRAL_ADHERENCE_IN_PAST_WEEK = "ANTIRETROVIRAL ADHERENCE IN PAST WEEK";

	String ANTIRETROVIRAL_DOSE_QUANTIFICATION = "ANTIRETROVIRAL DOSE QUANTIFICATION";

	String ANTIRETROVIRAL_PLAN = "ANTIRETROVIRAL PLAN";

	String ANTIRETROVIRAL_DRUGS = "ANTIRETROVIRAL DRUGS";

	String ANTIRETROVIRAL_DRUGS_USED_FOR_TREATMENT = "ANTIRETROVIRAL DRUGS USED FOR TREATMENT";

	String ANTIRETROVIRALS_STARTED = "ANTIRETROVIRALS STARTED";

	String BLOOD_TYPING = "BLOOD TYPING";

	String CD4_COUNT = "CD4 COUNT";

	String CD4_PANEL = "CD4 PANEL";

	String CD4_PERCENT = "CD4 PERCENT";

	String CHANGE_FORMULATION = "CHANGE FORMULATION";

	String CHEMISTRY_LAB_TESTS = "CHEMISTRY LAB TESTS";

	String COMPLETE_BLOOD_COUNT = "COMPLETE BLOOD COUNT";

	String CONTINUE_REGIMEN = "CONTINUE REGIMEN";

	String CURRENT_ANTIRETROVIRAL_DRUGS_USED_FOR_TRANSMISSION_PROPHYLAXIS = "CURRENT ANTIRETROVIRAL DRUGS USED FOR TRANSMISSION PROPHYLAXIS";

	String CURRENT_ANTIRETROVIRAL_DRUGS_USED_FOR_TREATMENT = "CURRENT ANTIRETROVIRAL DRUGS USED FOR TREATMENT";

	String CRYPTOCOCCAL_TREATMENT_PLAN = "CRYPTOCOCCAL TREATMENT PLAN";

	String CXR = "CXR";

	String CXR_CAVITARY_LESION = "CAVITARY LESION";

	String CXR_DIFFUSE_NON_MILIARY_CHANGES = "DIFFUSE NON-MILIARY CHANGES";

	String CXR_INFILTRATE = "INFILTRATE";

	String CXR_MILIARY_CHANGES = "MILIARY CHANGES";

	String CXR_PULMONARY_EFFUSION = "PULMONARY EFFUSION";

	String DAPSONE = "DAPSONE";

	String DEPOPROVERA = "DEPOPROVERA";

	String DID_NOT_RECIEVE_ANTENATAL_CARE_SERVICE_THIS_VISIT = "DID NOT RECIEVE ANTENATAL CARE SERVICE THIS VISIT";

	String DOSING_CHANGE = "DOSING CHANGE";

	String DRUG_RESTART = "DRUG RESTART";

	String DRUG_SUBSTITUTION = "DRUG SUBSTITUTION";

	String ELECTIVE_CAESAREAN_SECTION = "ELECTIVE CAESAREAN SECTION";

	String EMTRICITABINE_AND_TENOFOVIR = "EMTRICITABINE AND TENOFOVIR";

	String ESTIMATED_DATE_OF_CONFINEMENT = "ESTIMATED DATE OF CONFINEMENT";

	String EXPRESS_CARE_PROGRAM = "EXPRESS CARE PROGRAM";

	String FIRST_INTERMITTENT_PREVENTIVE_TREATMENT = "INTERMITTENT PREVENTIVE TREATMENT 1";

	String FLUCONAZOLE = "FLUCONAZOLE";

	String FOLIC_ACID = "FOLIC ACID";

	String HEMOGLOBIN = "HEMOGLOBIN";

	String HIV_DNA_POLYMERASE_CHAIN_REACTION_QUALITATIVE = "HIV DNA POLYMERASE CHAIN REACTION, QUALITATIVE";

	String HIV_ENZYME_IMMUNOASSAY_QUALITATIVE = "HIV ENZYME IMMUNOASSAY, QUALITATIVE";

	String HIV_INFECTED = "HIV INFECTED";

	String HIV_RAPID_TEST_QUALITATIVE = "HIV RAPID TEST, QUALITATIVE";

	String HIV_TEST_RESULT_PREVIOUSLY = "HIV TEST RESULT PREVIOUSLY";

	String HIV_TEST_RESULT_THIS_VISIT = "HIV TEST RESULT THIS VISIT";

	String HIV_VIRAL_LOAD_QUANTITATIVE = "HIV VIRAL LOAD, QUANTITATIVE";

	String IMMUNIZATIONS_COMPLETE = "IMMUNIZATIONS COMPLETE";

	String IMMUNIZATIONS_COMPLETED = "COMPLETED";

	String IMMUNIZATIONS_HISTORY = "IMMUNIZATION HISTORY";

	String IMMUNIZATIONS_ORDERED = "IMMUNIZATIONS ORDERED";

	String IMMUNIZATIONS_ORDERED_DETAILED = "IMMUNIZATIONS ORDERED, DETAILED";

	String INDIRECT_COOMBS_TEST = "INDIRECT COOMB'S TEST";

	String IRON_SUPPLEMENT = "IRON SUPPLEMENT";

	String ISONIAZID = "ISONIAZID";

	String ITRACONAZOLE = "ITRACONAZOLE";

	String LAST_MENSTRUAL_PERIOD_DATE = "LAST MENSTRUAL PERIOD DATE";

	String LAMIVUDINE_AND_TENOFOVIR = "LAMIVUDINE AND TENOFOVIR";

	String LOPINAVIR_AND_RITONAVIR = "LOPINAVIR AND RITONAVIR";

	String LOPINAVIR = "LOPINAVIR";

	String LOW_RISK_EXPRESS_CARE_PROGRAM = "LOW RISK EXPRESS CARE PROGRAM";

	String MATERNAL_PARTUM_ANTIRETROVIRAL_HISTORY = "MATERNAL PARTUM ANTIRETROVIRAL HISTORY";

	String MEAN_CORPUSCULAR_VOLUME = "MEAN CORPUSCULAR VOLUME";

	String MEDICATION_ADDED = "MEDICATION ADDED";

	String METHOD_OF_FAMILY_PLANNING = "METHOD OF FAMILY PLANNING";

	String MULTIDRUG_RESISTANT_TUBERCULOSIS_REGIMEN = "MULTIDRUG-RESISTANT TUBERCULOSIS REGIMEN";

	String MULTIVITAMIN = "MULTIVITAMIN";

	String NEGATIVE = "NEGATIVE";

	String NEVIRAPINE = "NEVIRAPINE";

	String NO = "NO";

	String NONE = "NONE";

	String NUMBER_OF_DOSES_RECEIVED_BEFORE_ENROLLMENT = "NUMBER OF DOSES RECEIVED BEFORE ENROLLMENT";

	String NUMBER_OF_DOSES_ORDERED = "NUMBER OF DOSES";

	String NUMBER_OF_WEEKS_PREGNANT = "NUMBER OF WEEKS PREGNANT";

	String NUMBER_OF_WEEKS_ON_TREATMENT = "NUMBER OF WEEKS ON TREATMENT";

	String NUTRITIONAL_SUPPORT = "NUTRITIONAL SUPPORT";

	String OBSTETRICS = "OBSTETRICS";

	String OVERALL_DRUG_ADHERENCE_IN_LAST_MONTH = "OVERALL DRUG ADHERENCE IN LAST MONTH";

	String PARTUM_ANTIRETROVIRAL_USE = "PARTUM ANTIRETROVIRAL USE";

	String PARTUM_DOSING_PERIOD = "PARTUM DOSING PERIOD";

	String PATIENT_REPORTED_CURRENT_PCP_PROPHYLAXIS = "PATIENT REPORTED CURRENT PCP PROPHYLAXIS";

	String PATIENT_REPORTED_CURRENT_TUBERCULOSIS_TREATMENT = "PATIENT REPORTED CURRENT TUBERCULOSIS TREATMENT";

	String PATIENT_REPORTED_PAST_ANTIRETROVIRAL_TREATMENT = "PATIENT REPORTED PAST ANTIRETROVIRAL TREATMENT";

	String PATIENT_REPORTED_PROBLEM_ADDED = "PATIENT REPORTED PROBLEM ADDED";

	String PCP_PROPHYLAXIS_STARTED = "PCP PROPHYLAXIS STARTED";

	String PCP_PROPHYLAXIS_PLAN = "PCP PROPHYLAXIS PLAN";

	String PEDIATRIC_STUDY_CONTROL_GROUP = "PEDIATRIC CONTROL";

	String PEDIATRIC_STUDY_INTERVENTION_GROUP = "PEDIATRIC INTERVENTION";

	String PEDS_WHO_CATEGORY_QUERY = "PEDS WHO CATEGORY QUERY";

	String PILLS = "PILLS";

	String POSITIVE = "POSITIVE";

	String PREFERRED_MODE_OF_DELIVERY = "PREFERRED MODE OF DELIVERY";

	String PRESENCE_OF_LEUKOCYTES = "PRESENCE OF LEUKOCYTES";

	String PRESENCE_OF_PROTEIN = "PRESENCE OF PROTEIN";

	String PRESENCE_OF_SUGAR = "PRESENCE OF SUGAR";

	String PREVIOUS_IMMUNIZATIONS_ADMINISTERED = "PREVIOUS IMMUNIZATIONS ADMINISTERED";

	String PROBLEM_ADDED = "PROBLEM ADDED";

	String PROBLEM_LIST_FOR_CLINICAL_SUMMARY = "PROBLEM LIST FOR CLINICAL SUMMARY";

	String PROBLEM_RESOLVED = "PROBLEM RESOLVED";

	String PYRAZINAMIDE = "PYRAZINAMIDE";

	String QUANTITY = "QUANTITY";

	String RECIEVED_ANTENATAL_CARE_SERVICE_THIS_VISIT = "RECIEVED ANTENATAL CARE SERVICE THIS VISIT";

	String REFERRALS_ORDERED = "REFERRALS ORDERED";

	String REFERRAL_CONSULTANT = "CONSULTANT";

	String REFERRAL_MEDICAL_OFFICER = "MEDICAL OFFICER";

	String REFILLED = "REFILLED";

	String RHESUS_FACTOR = "RHESUS FACTOR";

	String RETURN_VISIT_DATE = "RETURN VISIT DATE";

	String RIFAMPICIN = "RIFAMPICIN";

	String RITONAVIR = "RITONAVIR";

	String SECOND_INTERMITTENT_PREVENTIVE_TREATMENT = "INTERMITTENT PREVENTIVE TREATMENT 2";

	String SERUM_CREATININE = "SERUM CREATININE";

	String SERUM_ELECTROLYTES = "SERUM ELECTROLYTES";

	String SERUM_GLUTAMIC_PYRUVIC_TRANSAMINASE = "SERUM GLUTAMIC-PYRUVIC TRANSAMINASE";

	String SYPHILIS_VDRL_QUALITATIVE = "SYPHILIS - VDRL, QUALITATIVE";

	String START_DRUGS = "START DRUGS";

	String STOP_ALL = "STOP ALL";

	String TENOFOVIR = "TENOFOVIR";

	String TETANUS_BOOSTER = "TETANUS BOOSTER";

	String TETANUS_BOOSTER_COMPLETED = "TETANUS BOOSTER COMPLETED";

	String TETANUS_BOOSTER_DETAILED = "TETANUS BOOSTER, DETAILED";

	String TESTS_ORDERED = "TESTS ORDERED";

	String TRIMETHOPRIM_AND_SULFAMETHOXAZOLE = "TRIMETHOPRIM AND SULFAMETHOXAZOLE";

	String TUBERCULOSIS_PROPHYLAXIS_PLAN = "TUBERCULOSIS PROPHYLAXIS PLAN";

	String TUBERCULOSIS_TREATMENT_DRUGS = "TUBERCULOSIS TREATMENT DRUGS";

	String TUBERCULOSIS_TREATMENT_PLAN = "TUBERCULOSIS TREATMENT PLAN";

	String TUBERCULOSIS_DEFAULTER_REGIMEN_BY_USING_STREPTOMYCIN = "TUBERCULOSIS DEFAULTER REGIMEN BY USING STREPTOMYCIN";

	String TUBERCULOSIS_TREATMENT_STARTED = "TUBERCULOSIS TREATMENT STARTED";

	String WEIGHT_KG = "WEIGHT (KG)";

	String YES = "YES";

	// pediatric study location

	String PEDIATRIC_STUDY_LOCATION = "MTRH MODULE 4";

	String ANTENATAL_STUDY_LOCATION = "MOI TEACHING AND REFERRAL HOSPITAL";

	// list of all encounter types

	String ENCOUNTER_TYPE_ANCINITIAL = "ANCINITIAL";

	String ENCOUNTER_TYPE_ANCRETURN = "ANCRETURN";

	String ENCOUNTER_TYPE_ADULT_INITIAL = "ADULTINITIAL";

	String ENCOUNTER_TYPE_ADULT_RETURN = "ADULTRETURN";

	String ENCOUNTER_TYPE_ADULT_NONCLINICALMEDICATION = "ADULTNONCLINICALMEDICATION";

	String ENCOUNTER_TYPE_PEDIATRIC_INITIAL = "PEDSINITIAL";

	String ENCOUNTER_TYPE_PEDIATRIC_RETURN = "PEDSRETURN";

	String ENCOUNTER_TYPE_PEDIATRIC_NONCLINICALMEDICATION = "PEDSNONCLINICALMEDICATION";

	String ECHIGHRISK = "ECHIGHRISK";

	String ECSTABLE = "ECSTABLE";

	String ENCOUNTER_TYPE_MOSORIOT_PERINATAL_INITIAL = "MPerinatalInitial";

	String ENCOUNTER_TYPE_MOSORIOT_PRIMARY_CARE = "MRHCMain";

	String ENCOUNTER_TYPE_MOSORIOT_PERINATAL_RETURN = "MPerinatalReturn";

	String ENCOUNTER_TYPE_PRIMARY_CARE_MAIN = "PRIMARYCAREMAIN";
}
